spring:
  application:
    name: meal-planner
  datasource:
    url: jdbc:postgresql://localhost:5432/meal_planner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: "text-embedding-3-small"
