spring:
  application:
    name: meal-planner
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:postgresql://localhost:5432/meal_planner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: "gpt-5-mini"
          temperature: 1
      embedding:
        options:
          model: "text-embedding-3-small"

meal-planner:
  ai:
    low-cost-model: "gpt-4o-mini"
